/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as basicNftTwoSol from "./BasicNftTwo.sol";
export type { basicNftTwoSol };
export type { BasicNft } from "./BasicNft";
