/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as basicNFtTwoSol from "./BasicNFtTwo.sol";
export type { basicNFtTwoSol };
export type { BasicNft } from "./BasicNft";
