/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as nftMarketSol from "./NFTMarket.sol";
export type { nftMarketSol };
import type * as nftMarketplaceSol from "./NFTMarketplace.sol";
export type { nftMarketplaceSol };
import type * as test from "./test";
export type { test };
