/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as basicNFtTwoSol from "./BasicNFtTwo.sol";
export { BasicNft__factory } from "./BasicNft__factory";
