/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as basicNftTwoSol from "./BasicNftTwo.sol";
export { BasicNft__factory } from "./BasicNft__factory";
